package de.heisluft.cli.simplecli;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Arrays;

/**
 * This Exception is thrown whenever the {@link OptionParser} fails to parse a command line string
 * unambiguously. It always has a reason attached for easier handling.
 *
 * @since 0.1.0
 */
public class OptionParseException extends RuntimeException {
  /**
   * Denotes the reason why option parsing failed.
   */
  public enum Reason {
    /** An option was defined twice. */
    DUPLICATE_OPTION("Option %s is defined twice"),
    /** An option requiring a value did not have its value set. */
    MISSING_VALUE("Option %s requires a value, but none is given"),
    /** Multiple options declaring consumption of a value defined in same short option grouping. */
    ARG_GROUPING_CONFLICT("Multiple options requiring values defined in the same group '%s'"),
    /**
     * The given command is not recognized by this parser.
     *
     * @since 0.4.0
     */
    NO_MATCHING_COMMAND("'%s' is not a valid command"),
    /**
     * The given command does not accept the given option.
     *
     * @since 0.4.0
     */
    INVALID_OPTION("'%s' is not a valid option for the given command"),
    /**
     * If strict parsing is enabled, trailing strings on the command line error.
     *
     * @since 0.4.0
     */
    TRAILING_ARGUMENTS("Trailing arguments are not allowed: %s"),
    /**
     * The given command requires more arguments than were supplied.
     *
     * @since 0.4.0
     */
    MISSING_ARGUMENT("Command requires more arguments. Missing arguments: %s"),
    /**
     * Indicates an error while converting the raw string value to the final consumed value.
     * The option / argument name for which it failed is given as context.
     *
     * @since 0.4.0
     */
    CONVERSION_ERROR("Value '%s' could not be converted for %s"),
    /**
     * Indicates converting the raw string value to the final value produced null
     * at some stage. The option / argument name for which it failed is given as context.
     *
     * @since 0.4.0
     */
    NULL_VALUE("Value '%s' of %s converted to null"),
    /**
     * Indicates converting the raw string value to the final consumed value produced null.
     * The option / argument name for which it failed is given as context.
     *
     * @since 0.4.0
     */
    INVALID_VALUE("String '%s' did not produce a valid value for '%s': %s");

    /**
     * The template for constructing an exception message. {@code {0}} is substituted for the
     * offending options long name.
     */
    private final @NotNull String msgTemplate;

    /**
     * Constructor for the reason.
     *
     * @param msgTemplate The format string template for constructing an exception message.
     */
    Reason(@NotNull String msgTemplate) {
      this.msgTemplate = msgTemplate;
    }
  }

  /** The reason why parsing failed. */
  public final @NotNull Reason reason;
  /**
   * The string representation of the entity that caused parsing to fail.
   *
   * @since 0.2.0
   */
  public final @NotNull String offender;
  /**
   * The option / argument name associated with the failure. May be the same as {@link #offender}.
   *
   * @since 0.4.0
   */
  public final @NotNull String[] context;

  /**
   * Constructs a new instance. The message will be auto-generated by
   * {@link String#format(String, Object...)}
   *
   * @param reason the reason why parsing failed
   * @param offender the string representation of the entity that caused parsing to fail
   */
  OptionParseException(@NotNull Reason reason, @NotNull String offender) {
    this(null, reason, offender);
  }

  /**
   * Constructs a new instance. The message will be auto-generated by
   * {@link String#format(String, Object...)}.
   *
   * @param reason the reason why parsing failed
   * @param offender the string representation of the entity that caused parsing to fail
   * @param context The option / argument name associated with the failure. May be the same as offender
   *
   * @since 0.4.0
   */
  OptionParseException(@NotNull Reason reason, @NotNull String offender, @NotNull Object... context) {
    this(null, reason, offender, context);
  }

  /**
   * Constructs a new instance. The message will be auto-generated by
   * {@link String#format(String, Object...)}.
   *
   * @param reason the reason why parsing failed
   * @param offender the string representation of the entity that caused parsing to fail
   * @param context The option / argument name associated with the failure. May be the same as offender
   * @param cause The throwable leading to this exception being thrown
   *
   * @since 0.4.0
   */
  OptionParseException(
      @Nullable Throwable cause,
      @NotNull Reason reason,
      @NotNull String offender,
      @NotNull Object... context
      ) {
    this(cause, reason, concat(offender, context));
  }

  private OptionParseException(
      @Nullable Throwable cause,
      @NotNull Reason reason,
      @NotNull String[] context
  ) {
    super(String.format(reason.msgTemplate, (Object[]) context), cause);
    this.context = context;
    this.reason = reason;
    this.offender = context[0];
  }

  private static String[] concat(String first, Object[] additional) {
    String[] result = new String[additional.length + 1];
    result[0] = first;
    for(int i = 0; i < additional.length; i++) {
      Object item = additional[i];
      result[i + 1] = item instanceof Object[] ? Arrays.toString((Object[]) item) : item.toString();
    }
    return result;
  }
}
