package de.heisluft.cli.simplecli;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This Exception is thrown whenever the {@link OptionParser} fails to parse a command line string
 * unambiguously. It always has a reason attached for easier handling.
 *
 * @since 0.1.0
 */
public class OptionParseException extends RuntimeException {
  /**
   * Denotes the reason why option parsing failed.
   */
  public enum Reason {
    /** An option was defined twice. */
    DUPLICATE_OPTION("Option {0} is defined twice"),
    /** An option requiring a value did not have its value set. */
    MISSING_VALUE("Option {0} requires a value, but none is given"),
    /** Multiple options declaring consumption of a value defined in same short option grouping. */
    ARG_GROUPING_CONFLICT("Multiple options requiring values defined in the same group '{0}'"),
    /**
     * The given command is not recognized by this parser.
     *
     * @since 0.4.0
     */
    NO_MATCHING_COMMAND("'{0}' is not a valid command"),
    /**
     * The given command does not accept the given option.
     *
     * @since 0.4.0
     */
    INVALID_OPTION("'{0}' is not a valid option for the given command"),
    /**
     * If strict parsing is enabled, trailing strings on the command line error.
     *
     * @since 0.4.0
     */
    TRAILING_ARGUMENTS("Trailing arguments are not allowed: {0}"),
    /**
     * The given command requires more arguments than were supplied.
     *
     * @since 0.4.0
     */
    MISSING_ARGUMENT("Command requires more arguments. Missing arguments: {0}"),
    /**
     * Indicates an error while converting the raw string value to the final consumed value.
     * The option / argument name for which it failed is given as context.
     *
     * @since 0.4.0
     */
    CONVERSION_ERROR("Value '{0}' could not be converted for {1}"),
    /**
     * Indicates converting the raw string value to the final consumed value produced null.
     * The option / argument name for which it failed is given as context.
     *
     * @since 0.4.0
     */
    NULL_VALUE("Value '{0}' of {1} converted to null");

    /**
     * The template for constructing an exception message. {@code {0}} is substituted for the
     * offending options long name.
     */
    private final @NotNull String msgTemplate;

    /**
     * Constructor for the reason.
     *
     * @param msgTemplate The template for constructing an exception message. {@code {0}} is
     * substituted for the string representation of the offending entity in
     * {@link #getMessage(String, String...)}, all further numbers are substituted with message
     * dependent context.
     */
    Reason(@NotNull String msgTemplate) {
      this.msgTemplate = msgTemplate;
    }

    /**
     * Generates an error message based on this enum values template as well as the given input
     * string. The pattern {@code {0}} of the template is substituted with the input string.
     *
     * @param offender a string representation of the offending entity.
     * @param context optional context. this is only for message formatting and will not be stored.
     *
     * @return the error message string.
     */
    private @NotNull String getMessage(@NotNull String offender, @NotNull String... context) {
      String msg = msgTemplate.replace("{0}", offender);
      for(int i = 0; i < context.length; i++) {
        String arg = context[i];
        msg = msg.replace("{" + (i + 1) + "}", arg);
      }
      return msg;
    }
  }

  /** The reason why parsing failed. */
  public final @NotNull Reason reason;
  /**
   * The string representation of the entity that caused parsing to fail.
   *
   * @since 0.2.0
   */
  public final @NotNull String offender;
  /**
   * The option / argument name associated with the failure. May be the same as {@link #offender}.
   *
   * @since 0.4.0
   */
  public final @NotNull String name;

  /**
   * Constructs a new instance. The message will be auto-generated by
   * {@link Reason#getMessage(String, String...)}.
   *
   * @param reason the reason why parsing failed
   * @param offender the string representation of the entity that caused parsing to fail
   */
  OptionParseException(@NotNull Reason reason, @NotNull String offender) {
    this(reason, offender, offender, null);
  }

  /**
   * Constructs a new instance. The message will be auto-generated by
   * {@link Reason#getMessage(String, String...)}.
   *
   * @param reason the reason why parsing failed
   * @param offender the string representation of the entity that caused parsing to fail
   * @param name The option / argument name associated with the failure. May be the same as offender
   *
   * @since 0.4.0
   */
  OptionParseException(@NotNull Reason reason, @NotNull String offender, @NotNull String name) {
    this(reason, offender, name, null);
  }

  /**
   * Constructs a new instance. The message will be auto-generated by
   * {@link Reason#getMessage(String, String...)}.
   *
   * @param reason the reason why parsing failed
   * @param offender the string representation of the entity that caused parsing to fail
   * @param name The option / argument name associated with the failure. May be the same as offender
   * @param cause The throwable leading to this exception being thrown
   *
   * @since 0.4.0
   */
  OptionParseException(
      @NotNull Reason reason,
      @NotNull String offender,
      @NotNull String name,
      @Nullable Throwable cause) {
    super(reason.getMessage(offender, name), cause);
    this.name = name;
    this.reason = reason;
    this.offender = offender;
  }
}
