plugins {
    id 'java'
    id 'signing'
    id 'maven-publish'
    id 'checkstyle'
}

group 'de.heisluft.cli'
version '0.4.0-pre+10'

java {
  withSourcesJar()
  withJavadocJar()
}

repositories {
    mavenCentral()
}

checkstyle {
    configFile = project.file("checkstyle.xml")
    toolVersion = '12.3.1'
}

tasks.withType(JavaCompile.class).configureEach {
    options.encoding = 'UTF-8'
    sourceCompatibility = targetCompatibility = '1.8'
}

dependencies {
    compileOnly 'org.jetbrains:annotations:26.1.0'
}

tasks.withType(JavaCompile.class).configureEach {
    javaCompiler = javaToolchains.compilerFor(t -> t.languageVersion = JavaLanguageVersion.of(11))
    sourceCompatibility = targetCompatibility = 1.8
    options.encoding = 'UTF-8'
}

jar {
    manifest.attributes.put("Automatic-Module-Name", "de.heisluft.simple-cli")
    dependsOn(check)
}

publishing {
    repositories.maven {
        url mavenUrl
        credentials {
            username = mavenUsername
            password = mavenPassword
        }
        authentication.withType(BasicAuthentication)
    }
    publications.create('maven', MavenPublication) {
        it.from components.getByName('java')
    }
}

signing {
    useGpgCmd()
    sign publishing.publications.maven
}